env:
  browser: true
  es2021: true

parser: "@typescript-eslint/parser"

extends:
  # https://github.com/43081j/eslint-plugin-wc
  - plugin:wc/recommended
  - plugin:wc/best-practice
  # https://github.com/43081j/eslint-plugin-lit
  - plugin:lit/all
  # https://github.com/amilajack/eslint-plugin-compat
  - plugin:compat/recommended
  # https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin
  - plugin:@typescript-eslint/recommended
  # https://github.com/prettier/eslint-config-prettier
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

ignorePatterns:
  - test/**/*

plugins:
  # https://github.com/43081j/eslint-plugin-wc
  - wc
  # https://github.com/43081j/eslint-plugin-lit
  - lit
  # https://github.com/BenoitZugmeyer/eslint-plugin-html
  - html
  # https://github.com/amilajack/eslint-plugin-compat
  - compat
  # https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin
  - "@typescript-eslint"

settings:
  wc:
    elementBaseClasses: [LitElement]

rules:
  wc/guard-super-call: off
  wc/no-method-prefixed-with-on: error
